2) Подберите аргументы функции eval_model для логистической регрессии таким образом, чтобы log loss был минимальным.

In [46]:
import numpy as np
import pandas as pd

In [2]:
X = np.array([ [   1,    1,  500,    1],
               [   1,    1,  700,    1],
               [   1,    2,  750,    2],
               [   1,    5,  600,    1],
               [   1,    3, 1450,    2],
               [   1,    0,  800,    1],
               [   1,    5, 1500,    3],
               [   1,   10, 2000,    3],
               [   1,    1,  450,    1],
               [   1,    2, 1000,    2]], dtype=np.float64)

y = np.array([0, 0, 1, 0, 1, 0, 1, 0, 1, 1], dtype=np.float64)

In [3]:
X

array([[1.00e+00, 1.00e+00, 5.00e+02, 1.00e+00],
       [1.00e+00, 1.00e+00, 7.00e+02, 1.00e+00],
       [1.00e+00, 2.00e+00, 7.50e+02, 2.00e+00],
       [1.00e+00, 5.00e+00, 6.00e+02, 1.00e+00],
       [1.00e+00, 3.00e+00, 1.45e+03, 2.00e+00],
       [1.00e+00, 0.00e+00, 8.00e+02, 1.00e+00],
       [1.00e+00, 5.00e+00, 1.50e+03, 3.00e+00],
       [1.00e+00, 1.00e+01, 2.00e+03, 3.00e+00],
       [1.00e+00, 1.00e+00, 4.50e+02, 1.00e+00],
       [1.00e+00, 2.00e+00, 1.00e+03, 2.00e+00]])

In [4]:
y

array([0., 0., 1., 0., 1., 0., 1., 0., 1., 1.])

In [5]:
def standard_scale(x):
    res = (x - x.mean()) / x.std()
    return res

In [6]:
X_st = X.copy()
X_st[:, 2] = standard_scale(X[:, 2])

In [7]:
X_st

array([[ 1.        ,  1.        , -0.97958969,  1.        ],
       [ 1.        ,  1.        , -0.56713087,  1.        ],
       [ 1.        ,  2.        , -0.46401617,  2.        ],
       [ 1.        ,  5.        , -0.77336028,  1.        ],
       [ 1.        ,  3.        ,  0.97958969,  2.        ],
       [ 1.        ,  0.        , -0.36090146,  1.        ],
       [ 1.        ,  5.        ,  1.08270439,  3.        ],
       [ 1.        , 10.        ,  2.11385144,  3.        ],
       [ 1.        ,  1.        , -1.08270439,  1.        ],
       [ 1.        ,  2.        ,  0.05155735,  2.        ]])

In [8]:
def calc_logloss(y, y_pred):
    err = - np.mean(y * np.log(y_pred) + (1.0 - y) * np.log(1.0 - y_pred))
    return err

In [9]:
def sigmoid(z):
    res = 1 / (1 + np.exp(-z))
    return res

In [10]:
def eval_model(X, y, iterations, eta=1e-4):
    np.random.seed(42)
    W = np.random.randn(X.shape[1])
    n = X.shape[0]
    
    for i in range(iterations):
        z = np.dot(X, W)
        y_pred = sigmoid(z)
        err = calc_logloss(y, y_pred)
        
        dQ = 1/n * X.T @ (y_pred - y)
        W -= eta * dQ
        if i % (iterations / 10) == 0:
            print(i, W, err)
    return W

In [21]:
W = eval_model(X_st, y, iterations=1000, eta=1e-2)

0 [ 0.49292028 -0.15277306  0.64741473  1.51736839] 1.1785958344356262
100 [ 0.29954562 -0.70184086  0.66393101  1.28809857] 0.5200176817937363
200 [ 0.21783205 -0.71711535  0.72830416  1.28039917] 0.5083938298746018
300 [ 0.15081179 -0.71601562  0.78172777  1.29014996] 0.500908097886405
400 [ 0.09214433 -0.71718068  0.82443144  1.306414  ] 0.49535059743739646
500 [ 0.03982235 -0.72064774  0.8585723   1.32719824] 0.49098749514946327
600 [-0.00760312 -0.72573949  0.88595525  1.35123708] 0.48737496424720916
700 [-0.05125883 -0.73192167  0.90799082  1.37755197] 0.4842468146117195
800 [-0.0920137  -0.7388      0.92576955  1.40539219] 0.4814434848660955
900 [-0.13053215 -0.7460864   0.94013195  1.43419101] 0.47886846544307693


In [22]:
W = eval_model(X_st, y, iterations=1000, eta=1e-1)

0 [ 0.45877546 -0.2833519   0.6449505   1.46641523] 1.1785958344356262
100 [-0.17125771 -0.75500557  0.95514621  1.46737781] 0.47637022522305916
200 [-0.49499498 -0.82228902  0.98771187  1.75091919] 0.4571095488752876
300 [-0.79114327 -0.86672849  0.9559449   1.99242216] 0.442155509508474
400 [-1.07283403 -0.8947842   0.89607477  2.20060724] 0.4294239136608901
500 [-1.34177406 -0.91270843  0.82133512  2.38589737] 0.41815201612293285
600 [-1.59879514 -0.92438132  0.73899152  2.55492565] 0.4079867442724603
700 [-1.8445955  -0.93221288  0.65341638  2.71191591] 0.39873361980739686
800 [-2.07982431 -0.93772855  0.56729987  2.85964168] 0.39026644444254893
900 [-2.3051012  -0.94190303  0.48229109  2.99997387] 0.3824917038687346


Думаю, лучше остановиться на 1000 повторениях при eta=1e-2

3) Создайте функцию calc_pred_proba, возвращающую предсказанную вероятность класса 1 (на вход подаются W, который уже посчитан функцией eval_model и X, на выходе - массив y_pred_proba).

In [38]:
def calc_pred_proba(W, X):
    return sigmoid(np.dot(W, X.T))

In [39]:
y_pred_proba = calc_pred_proba(W, X_st)
y_pred_proba

array([0.34932779, 0.16427547, 0.99728909, 0.00125889, 0.73167283,
       0.32275025, 0.99921549, 0.09094949, 0.4083464 , 0.99054589])

4) Создайте функцию calc_pred, возвращающую предсказанный класс (на вход подаются W, который уже посчитан функцией eval_model и X, на выходе - массив y_pred).

In [40]:
def calc_pred(W, X, p = 0.5):
    y_pred = calc_pred_proba(W, X)
    y_pred = np.where(y_pred > p, 1, 0 )
    return y_pred

In [43]:
y_pred = calc_pred(W, X_st)
y_pred

array([0, 0, 1, 0, 1, 0, 1, 0, 0, 1])

5) *Реализуйте функции для подсчета Accuracy, матрицы ошибок, точности и полноты, а также F1 score.

In [44]:
accuracy = np.sum(y_pred)/y_pred.shape[0] 
accuracy

0.4

In [47]:
conf_matrix = np.array(pd.crosstab(y, y_pred)) # матрица ошибок
conf_matrix

array([[5, 0],
       [1, 4]], dtype=int64)

In [52]:
precision = conf_matrix[1, 1] / (conf_matrix[1, 1] + conf_matrix[0, 1])
precision

1.0

In [53]:
recall = conf_matrix[1, 1] / (conf_matrix[1, 1] + conf_matrix[1, 0])
recall

0.8

$$F = \frac{2 \cdot precision \cdot recall }{ presision + recall}.$$

In [56]:
f1 = (2 * precision * recall) / (precision + recall)
f1

0.888888888888889